# pyproject.toml

[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "othello"
version = "1.0.0"

# Read file in python : https://realpython.com/python-toml/